A=int(input("Enter the first number: "))
B=int(input("Enter the second number: "))
print("Addition: ",A+B)
print("Subtraction: ",A-B)
print("Multiplication: ",A*B)
print("Division: ",A/B)
print()
C=str(input("Enter the First Name: "))
D=str(input("Enter the Second Name: "))
print("HELLO, " + C +" "+ D + "! WELCOME TO PYTHON CLASS ")